name: CI Check

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: zulu
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Spotless Check
      run: ./gradlew spotlessCheck
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run unit tests
      run: ./gradlew test
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: ./app/build/outputs/apk/release/app-release-unsigned.apk
        if-no-files-found: error
